version: '3'

services:
  # PHP application container
  lumen:
    container_name: lumen
    build: container/php
    image: php:own
    depends_on:
      - db
      - elastic
    volumes:
      - ./:/app:cached
      - ./container/php/php.ini-production:/usr/local/etc/php/conf.d/10-custom.ini
    networks:
      - app_network

  db:
    container_name: bot_db
    image: postgres:14.2-alpine3.15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./container/data/pgsql/:/var/lib/postgresql/data/pgdata
    networks:
      - app_network
    ports:
      - "6432:5432"
    restart: on-failure

  # Web Server
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
    depends_on:
      - lumen
    networks:
      - app_network

  elastic:
    container_name: elastic
    build: container/elastic
    environment:
      - "node.name=location-bot-master"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./container/data/elastic:/usr/share/elasticsearch/data
      - ./container/elastic/config/synonyms:/usr/share/elasticsearch/config/synonyms
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    driver: "bridge"
