version: '3.8'

services:
  # PHP application container
  lumen:
    container_name: lumen
    build:
      context: container/php
    image: bot_backend:latest
    depends_on:
      - db
    volumes:
      - ./:/app:delegated
    networks:
      - app_network

  db:
    container_name: bot_db
    image: postgres:14.2-alpine3.15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./container/data/pgsql/:/var/lib/postgresql/data/pgdata
    networks:
      - app_network
    restart: on-failure

  # Web Server
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
    depends_on:
      - lumen
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: "bridge"
