version: '3.8'

services:
  # PHP application container
  lumen:
    container_name: lumen
    build:
      context: container/php
      target: develop
    image: bot_backend:latest
    depends_on:
      - mysql
    volumes:
      - ./:/app:delegated
    networks:
      - app_network

  # Database container
  mysql:
    container_name: bot_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./container/data/mysql:/var/lib/mysql
    networks:
      - app_network
    restart: always

  backuper:
    build: container/backuper
    container_name: database-backup
    env_file:
      - .env
    volumes:
      - ./container/data/backup:/opt/mysql/backup
    command: crond -f -d 8
    restart: always

  # Web Server
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
    depends_on:
      - lumen
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: "bridge"
