version: '3'

services:
  # PHP application container
  lumen:
    container_name: lumen
    build: .container/docker/php
    image: php:own
    depends_on:
      - mysql
    volumes:
      - ./:/app:cached
    networks:
      - app_network

  # Database container
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql:cached
    networks:
      - app_network

  # Web Server
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .container/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
    depends_on:
      - lumen
    networks:
      - app_network

  elastic:
    container_name: elastic
    build: .container/docker/elastic
    image: elasticsearch:ukr
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: "bridge"
