name: Bot Deploy
run-name: Deploying new version 

on: workflow_dispatch

jobs:
  ssh-command:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          ssh-add ssh_key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Execute SSH Command
        run: |
          ssh -o StrictHostKeyChecking=no -A ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_IP }} 'echo Hello >> file.txt'
